version: "3"

services:
  postgres-docker:
    image: postgres
    container_name: RedisSessionPostgres
    volumes:
      - ${POSTGRES_HOST_DIR}:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - netcore-dev

  redis-docker:
    image: redis
    container_name: RedisSessionRedis
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_HOST_DIR}:/data
    networks:
      - netcore-dev
        
  netcore:
    image: aspnetredissession:dev
    container_name: AspNetRedisSession
    ports:
      - "${HOST_PORT}:80"
    build:
      context: ../
      dockerfile: ./Dockerfile
    tty: true
    networks:
      - netcore-dev
    depends_on:
      - postgres-docker
      - redis-docker

networks:
  netcore-dev:
    driver: bridge
